#!/bin/bash

sudo pacman -S xorg xorg-xinit alacritty firefox dmenu make picom feh base-devel

./write_xinit

./add_fonts

./wallpapers

./neovim_conf

cd
cd .config/dwm-6.3
sudo make && sudo make clean install

