#!/bin/bash
cd
mkdir media
mkdir media/wallpapers
sudo pacman -S python-pywal
touch .Xresources
sudo pacman -S xdotool
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay -S python-pywalfox
pywalfox install
yay -S wal-telegram-git
