#!/bin/bash
mkdir -p /home/$USER/media/wallpapers
sudo pacman -S python-pywal
touch /home/$USER/.Xresources
sudo pacman -S xdotool
cd
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay -S python-pywalfox
pywalfox install
yay -S wal-telegram-git
