#!/bin/bash
mkdir -p $HOME/media/wallpapers
sudo pacman -S python-pywal
touch $HOME/.Xresources
sudo pacman -S xdotool
cd
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay -S python-pywalfox
pywalfox install
yay -S wal-telegram-git
