#!/bin/bash

cd
#git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons

#echo "default_linemode devicons" >> $HOME/.config/ranger/rc.conf
(cat $HOME/.config/dop_file/script/start/ranger_conf) >> $HOME/.bashrc
